# Generated by Django 5.2.1 on 2025-08-01 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=50)),
                ('car_description', models.TextField(max_length=350)),
                ('car_img', models.ImageField(blank=True, null=True, upload_to='media_files/')),
                ('car_price', models.CharField()),
                ('car_quantity', models.IntegerField()),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand_app.brandmodel')),
            ],
        ),
    ]
